version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: lodash
    versions:
    - 4.17.20
